petstagram/pets/urls.py
from django.urls import path, include
from pets import views

app_name = 'pets'

urlpatterns = [
    path('add/', views.PetAddView.as_view(), name='add'),
    path('<str:username>/pet/<slug:pet_slug>/', include([
        path('', views.PetDetailView.as_view(), name='details'),
        path('edit/', views.PetEditView.as_view(), name='edit'),
        path('delete/', views.PetDeleteView.as_view(), name='delete'),
    ]))
]

petstagram/petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('accounts/', include('accounts.urls')),
    path('pets/', include('pets.urls')),
    path('photos/', include('photos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petstagram/pets/models.py
from django.db import models
from django.utils.text import slugify


class Pet(models.Model):
    name = models.CharField(
        max_length=30,
    )

    personal_photo = models.URLField()

    date_of_birth = models.DateField(
        blank=True,
        null=True,
    )

    slug = models.SlugField(
        unique=True,
        blank=True,
        editable=False,
    )

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(f"{self.name}-{self.pk}")
        super().save(*args, **kwargs)

petstagram/photos/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from photos.validators import FileSizeValidator


class Photo(models.Model):
    photo = models.ImageField(
        upload_to='media',
        validators=[
            FileSizeValidator(5),
        ]
    )

    description = models.CharField(
        max_length=100,
        validators=[
            MinLengthValidator(10),
        ],
        null=True,
        blank=True,
    )

    location = models.CharField(
        max_length=30,
    )

    tagged_pets = models.ManyToManyField(
        to="pets.Pet",
    )

    date_of_publication = models.DateField(
        auto_now=True,
    )

petstagram/pets/forms.py
from django import forms
from pets.models import Pet


class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'date_of_birth', 'personal_photo']

        labels = {
            'name': 'Pet Name',
            'date_of_birth': 'Date of Birth',
            'personal_photo': 'Image',
        }

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter pet name'}),
            'date_of_birth': forms.DateInput(attrs={'type': 'date'}),
            'personal_photo': forms.URLInput(attrs={'placeholder': 'Enter pet image'}),
        }


class PetDeleteForm(PetForm):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['disabled'] = True
            field.widget.attrs['readonly'] = True

petstagram/pets/views.py
from django.db.models import Prefetch
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from pets.forms import PetForm
from pets.models import Pet
from photos.models import Photo


class PetAddView(CreateView):
    model = Pet
    form_class = PetForm
    template_name = 'pets/pet-add-page.html'
    success_url = reverse_lazy('accounts:details', kwargs={"pk": 1})


# def pet_add(request: HttpRequest) -> HttpResponse:
#     form = PetForm(request.POST or None)
#
#     if request.method == "POST" and form.is_valid():
#         form.save()
#         return redirect('accounts:details', pk=1)
#
#     context = {
#         "form": form,
#     }
#
#     return render(request, 'pets/pet-add-page.html', context)



class PetDetailView(DetailView):
    queryset = Pet.objects.prefetch_related(
        Prefetch(
            'photo_set',
            queryset=Photo.objects.prefetch_related('tagged_pets', 'like_set')
        )
    )
    slug_url_kwarg = "pet_slug"
    template_name = "pets/pet-details-page.html"


# def pet_details(request: HttpRequest, username: str, pet_slug: str) -> HttpResponse:
#     pet = Pet.objects.prefetch_related(
#         Prefetch(
#             'photo_set',
#             queryset=Photo.objects.prefetch_related('tagged_pets', 'like_set')
#         )
#     ).get(slug=pet_slug)
#
#     context = {
#         "pet": pet,
#     }
#
#     return render(request, 'pets/pet-details-page.html', context)


class PetEditView(UpdateView):
    model = Pet
    form_class = PetForm
    slug_url_kwarg = "pet_slug"
    template_name = "pets/pet-edit-page.html"

    def get_success_url(self) -> str:
        return reverse(
            'pets:details',
            kwargs={
                "username": 'username', "pet_slug": self.object.slug
            }
        )

#
# def pet_edit(request: HttpRequest, username: str, pet_slug: str) -> HttpResponse:
#     pet = Pet.objects.get(slug=pet_slug)
#     form = PetForm(request.POST or None, instance=pet)
#
#     if request.method == "POST" and form.is_valid():
#         instance = form.save()
#         return redirect('pets:details', username='username', pet_slug=instance.slug)
#
#     context = {
#         'pet': pet,
#         'form': form,
#     }
#
#     return render(request, 'pets/pet-edit-page.html', context)


class PetDeleteView(DeleteView):
    model = Pet
    form_class = PetForm
    slug_url_kwarg = "pet_slug"
    template_name = "pets/pet-delete-page.html"
    success_url = reverse_lazy('accounts:details', kwargs={"pk": 1})

    def get_initial(self):
        return self.object.__dict__

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["form"] = PetForm(instance=self.object)
    #     return context

#
# def pet_delete(request: HttpRequest, username: str, pet_slug: str) -> HttpResponse:
#     pet = Pet.objects.get(slug=pet_slug)
#     form = PetForm(request.POST or None, instance=pet)
#
#     if request.method == "POST" and form.is_valid():
#         pet.delete()
#         return redirect('accounts:details', pk=1)
#
#     context = {
#         'pet': pet,
#         'form': form,
#     }
#
#     return render(request, 'pets/pet-delete-page.html', context)

petstagram/templates/pets/pet-add-page.html
{% extends 'shared/base.html' %}

{% block content %}
    <!-- Start Add Pet Section-->
    <div class="edit-delete edit-photo">
        <h2>Add pet</h2>

        <!-- Start Add Pet Form -->
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <!-- Add Pet Button -->
            <button class="add-btn" type="submit">Add Pet</button>
        </form>
        <!-- End Add Pet Form -->

    </div>
    <!-- End Add Pet Section -->
{% endblock %}

petstagram/templates/pets/pet-delete-page.html
{% extends 'shared/base.html' %}

{% block content %}
    <!-- Starts Delete Pet Section -->
    <div class="edit-delete edit-photo">
        <h2>Delete pet</h2>
        <!-- Starts Delete Pet Form -->
        <form method="post">
            {{ form }}
            {% csrf_token %}
            <!-- Delete Pet Button -->
            <button class="delete-btn" type="submit">Delete</button>
            <!-- Go Back Button -->
            <a class="btn btn-primary" href="javascript:history.back()">
                <button class="edit-btn" type="button">Go back</button>
            </a>
        </form>
        <!-- End Delete Pet Form -->
    </div>
{% endblock %}

petstagram/templates/pets/pet-details-page.html
{% extends 'shared/base.html' %}

{% block content %}
    <div class="pet-profile">
        <!-- Start Pet Personal Data Section -->
        <div class="profile">
            <div class="profile-data">
                <div class="profile_img">
                    <div class="image">
                        <!-- Pet URL Image -->
                        <img src="https://encrypted-tbn0.gstatic.com/static/images?q=tbn:ANd9GcTgoIHq82qLYnvomfz5ZkW5CLQ8VNxCyI-hUw&usqp=CAU"
                             alt="img8">
                    </div>
                </div>
                <div class="personal">
                    <div class="edit">
                        <!-- Pet Name -->
                        <p>{{ pet.name }}</p>
                        <!-- Pet Edit Button -->
                        <a href="{% url 'pets:edit' username='username' pet_slug=pet.slug %}">
                            <img class="edit-img" src="/static/images/edit-pen-icon-6.jpg" alt="edit button">
                        </a>
                        <!-- Pet Delete Button -->
                        <a href="{% url 'pets:delete' username='username' pet_slug=pet.slug %}">
                            <img class="bin-img" src="/static/images/icon-remove-22.jpg" alt="bin button">
                        </a>
                    </div>
                    <div class="data">
                        <!-- Pet Total Photos -->
                        <span>{{ pet.photo_set.count }}</span>
                        <p>photos</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="pet-posts">
            {% for photo in pet.photo_set.all %}
                {% include 'common/pet-posts.html' %}
            {% empty %}
                <img class="no-posts" src="/static/images/no_posts.png" alt="no posts image">
            {% endfor %}
        </div>
    </div>
{% endblock %}

petstagram/templates/pets/pet-edit-page.html
{% extends 'shared/base.html' %}

{% block content %}
    <!-- Start Edit Pet Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit Pet</h2>
        <!-- Start Edit Pet From -->
        <form method="post">
            {{ form }}
            {% csrf_token %}
            <!-- Edit Pet Button -->
            <button class="edit-btn" type="submit">Edit</button>
        </form>
        <!-- End Edit Pet Form -->

    </div>
    <!-- End Edit Pet Section -->
{% endblock %}