petstagram/common/urls.py
from django.urls import path
from common import views

app_name = 'common'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('<int:photo_pk>/like/', views.like_functionality, name='like'),
    path('<int:photo_pk>/share/', views.share_functionality, name='share'),
    path('<int:photo_pk>/comment/', views.add_comment, name='add-comment'),
]

petstagram/pets/urls.py
from django.urls import path, include
from pets import views

app_name = 'pets'

urlpatterns = [
    path('add/', views.PetAddView.as_view(), name='add'),
    path('<str:username>/pet/<slug:pet_slug>/', include([
        path('', views.PetDetailView.as_view(), name='details'),
        path('edit/', views.PetEditView.as_view(), name='edit'),
        path('delete/', views.PetDeleteView.as_view(), name='delete'),
    ]))
]

petstagram/petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('accounts/', include('accounts.urls')),
    path('pets/', include('pets.urls')),
    path('photos/', include('photos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petstagram/photos/urls.py
from django.urls import path, include
from photos import views

app_name = 'photos'

urlpatterns = [
    path('add/', views.photo_add, name='add'),
    path('<int:pk>/', include([
        path('', views.photo_details, name='details'),
        path('edit/', views.photo_edit, name='edit'),
        path('delete/', views.photo_delete, name='delete'),
    ])),
]

petstagram/common/models.py
from django.db import models


class Comment(models.Model):
    text = models.CharField(
        max_length=300,
    )

    date_and_time_of_publication = models.DateTimeField(
        auto_now_add=True,
    )

    to_photo = models.ForeignKey(
        "photos.Photo",
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = ['-date_and_time_of_publication']


class Like(models.Model):
    to_photo = models.ForeignKey(
        "photos.Photo",
        on_delete=models.CASCADE,
    )

petstagram/common/forms.py
from django import forms

from common.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'placeholder': 'Add comment...'})
        }


class SearchForm(forms.Form):
    pet_name = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Search by pet name...'}),
    )

petstagram/common/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, resolve_url
from django.views.generic import ListView
from pyperclip import copy

from common.forms import CommentForm, SearchForm
from common.models import Like, Comment
from photos.models import Photo


class HomePageView(ListView):
    queryset = Photo.objects.prefetch_related('tagged_pets', 'like_set')
    context_object_name = "all_photos"
    template_name = "common/home-page.html"
    paginate_by = 1

    def get_queryset(self):
        qs = super().get_queryset()
        pet_name = self.request.GET.get('pet_name')

        if pet_name:
            qs = qs.filter(tagged_pets__name__icontains=pet_name)

        return qs

#
# def home_page(request: HttpRequest) -> HttpResponse:
#     form = SearchForm(request.GET or None)
#     all_photos = Photo.objects.prefetch_related('tagged_pets', 'like_set')
#
#     if request.GET and form.is_valid():
#         searched_name = form.cleaned_data['pet_name']
#         all_photos = all_photos.filter(tagged_pets__name__icontains=searched_name)
#
#     context = {
#         'all_photos': all_photos,
#     }
#
#     return render(request, 'common/home-page.html', context)


def add_comment(request: HttpRequest, photo_pk: int) -> HttpResponse:
    if request.method == "POST":
        photo = Photo.objects.get(pk=photo_pk)
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.to_photo = photo
            comment.save()

        return redirect(request.META.get('HTTP_REFERER') + f'#{photo_pk}')


def like_functionality(request, photo_pk: int) -> HttpResponse:
    like_object = Like.objects.filter(to_photo_id=photo_pk).first()

    if like_object:
        like_object.delete()
    else:
        Like.objects.create(
            to_photo_id=photo_pk,
        )

    return redirect(request.META.get('HTTP_REFERER') + f'#{photo_pk}')


def share_functionality(request, photo_pk: int) -> HttpResponse:
    # This will work only on localhost as it copies the value on the server
    copy(request.META.get('HTTP_REFERER')[:-1] + resolve_url('photos:details', photo_pk))
    return redirect(request.META.get('HTTP_REFERER') + f'#{photo_pk}')

petstagram/templates/common/home-page.html
{% extends 'shared/base.html' %}
{% load query_extender %}

{% block content %}
    <div class="container">
        <div class="col-9">

            <!-- Start Searchbar Form -->
            <form class="searchbar">
                <input type="text" name="pet_name" placeholder="Search by pet name...">
                <button>
                    <img src="/static/images/search.png" height="18" alt="img2">
                </button>
            </form>
            <!-- End Searchbar Form -->
            {% for photo in all_photos %}
                {% include 'common/pet-posts.html' %}
            {% endfor %}
        
            <div class="pagination">
                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>
            
                <span class="step-links-buttons">
                
                    <!-- If there are previous and next photos -->
                    {% if page_obj.has_previous and page_obj.has_next %}
                        <a href="{% query_param_add "page" page_obj.previous_page_number %}">
                            <i class="fa-solid fa-arrow-left"></i>
                        </a>
                        <a href="{% query_param_add "page" page_obj.next_page_number %}">
                            <i class="fa-solid fa-arrow-right"></i>
                        </a>
                        
                    <!-- If there are only previous photos -->
                    {% elif page_obj.has_previous %}
                        <a href="{% query_param_add "page" page_obj.previous_page_number %}">
                            <i class="fa-solid fa-arrow-left"></i>
                        </a>

                    <!-- If there are only next photos -->
                    {% elif page_obj.has_next %}
                        <a href="{% query_param_add "page" page_obj.next_page_number %}">
                            <i class="fa-solid fa-arrow-right"></i>
                        </a>
                    {% endif %}
                
                </span>
            </div>
            <!-- End Pet Photos Post Section -->
        </div>
    </div>
{% endblock %}

petstagram/templates/common/pet-posts.html
<div class="card">
    <div class="top">
        <!-- User Details and image location -->
        <div class="userDetails">
            <a href="profile details">
                <div class="profilepic">
                    <div class="profile_img">
                        <div class="image">
                            <img src="/static/images/person.png" alt="img8">
                        </div>
                    </div>
                </div>
            </a>
            <h3>
                <a href="profile details">
                    <!-- if user has first name and last name -->
                    Diyan Kalaydzhiev
                    <!-- else -->
                    <!-- user username -->
                </a>
                <br>
                <!-- if the photo has location -->
                <span>{{ photo.location }}</span>
            </h3>
            {% if editable %}
                <div class="edit-delete-btns">
    
                    <!-- Link to Edit Pet Photo Page -->
                    <a href="{% url 'photos:edit' photo.pk %}">
                        <img class="edit-img" src="/static/images/edit-pen-icon-6.jpg"
                             alt="edit button">
                    </a>
    
                    <!-- Link to Delete Pet Photo Page -->
                    <a href="{% url 'photos:delete' photo.pk %}">
                        <img class="bin-img" src="/static/images/icon-remove-22.jpg" alt="bin button">
                    </a>
                </div>
            {% endif %}
        </div>
        <!--  -->
    </div>
    <!-- Post image -->
    <div class="imgBx" id="{{ photo.pk }}">
        <img src="{{ photo.photo.url }}" alt="post" class="cover">
    </div>
    <!-- -->

    <div class="bottom">
        <!-- like and share buttons -->
        <div class="actionBtns">
            <div class="left">
                    <span class="heart">
                        <a href="{% url 'common:like' photo.pk %}">
                            {% if photo.like_set.count %}
                                <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                            {% else %}
                                <i class="fa-regular fa-heart"></i>
                            {% endif %}
                        </a>
                    </span>
                <a href="{% url 'common:share' photo.pk %}">
                    <i class="fa-solid fa-share"></i>
                </a>
            </div>
        </div>
        <!-- -->

        <a href="#">
            <p class="likes">{{ photo.like_set.count }} likes</p>
        </a>
        
        {% for tagged_pet in photo.tagged_pets.all %}
            <a href="{% url 'pets:details' username='username' pet_slug=tagged_pet.slug %}">
                <p class="message">
                    <b>{{ tagged_pet.name }}</b>
                </p>
            </a>
        {% endfor %}

        <a href="{% url 'photos:details' photo.pk %}">
            <h4 class="details">See details</h4>
        </a>

        <h5 class="postTime">{{ photo.date_of_publication }}</h5>
    
        {% if editable %}
           {% for comment in photo.comment_set.all %}
            <div class="comments">
                    <div class="top">
                        <div class="userDetails">
                            <div class="comment-data">
                                <div class="profilepic">
                                    <div class="profile_img">
                                        <div class="image">
                                            <!-- User Profile Image -->
                                            <img src="/static/images/person.png" alt="img8">
                                        </div>
                                    </div>
                                </div>
                                <p>
                                    <!-- Link to User Profile Details Page-->
                                    <!-- User First and/or Last Name or username-->
                                    <a href="">Steven Ivanov</a>
                                    <!-- User Comment -->
                                    - {{ comment.text }}
                                </p>
                            </div>
                            <span>{{ comment.date_and_time_of_publication|date:'M. d, Y, h:m a' }}</span>
                        </div>
                    </div>
               </div>
            {% endfor %}
        {% endif %}

        <!-- add comments section -->
        <div class="addComments">

            <form method="post" action="{% url 'common:add-comment' photo.pk %}">
                {% csrf_token %}
                <label for="id_body">Body:</label>
                <textarea name="text" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                          required="" id="id_text"></textarea>
                <button type="submit">Post</button>
            </form>
        </div>
        <!--  -->
    </div>
</div>